# Generated by Django 4.2.13 on 2024-05-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Credential',
        ),
    ]
