# Generated by Django 4.2.13 on 2024-05-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_users_credential'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credential',
            new_name='User',
        ),
    ]
